#pragma once

#define VIRT_FLASH_MEM_SIZE 0x100000
#define VIRT_FLASH_MEM_BASE 0x00800000

#define VIRT_FLASH_MEM_PROG_OFFSET 0x00020000

#if defined(ICE_ZERO) || defined (ICE40HX8K_EVB)
#undef  VIRT_FLASH_MEM_PROG_OFFSET
#define VIRT_FLASH_MEM_PROG_OFFSET 0x00030000
#endif

#define VIRT_FLASH_MEM_START (VIRT_FLASH_MEM_BASE + VIRT_FLASH_MEM_PROG_OFFSET)
#define VIRT_FLASH_MEM_LEN  (VIRT_FLASH_MEM_SIZE - VIRT_FLASH_MEM_PROG_OFFSET)
